// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Guest documents */
interface GuestDocumentData {
    /**
     * Name field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Avatar field in *Guest*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.avatar
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    avatar: prismicT.ImageField<never>;
    /**
     * Job Title field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.jobTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    jobTitle: prismicT.KeyTextField;
    /**
     * Guest Bio field in *Guest*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.guestBio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    guestBio: prismicT.RichTextField;
    /**
     * Twitter URL field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.twitterUrl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    twitterUrl: prismicT.KeyTextField;
    /**
     * Website URL field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.websiteUrl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    websiteUrl: prismicT.KeyTextField;
    /**
     * Mastadon URL field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.mastadonUrl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    mastadonUrl: prismicT.KeyTextField;
    /**
     * Topic Title field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.topicTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    topicTitle: prismicT.KeyTextField;
    /**
     * Topic Description field in *Guest*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.topicDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    topicDescription: prismicT.RichTextField;
}
/**
 * Guest document from Prismic
 *
 * - **API ID**: `guest`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GuestDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<GuestDocumentData>, "guest", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Page title
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
    /**
     * Metatitle field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.metatitle
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metatitle: prismicT.KeyTextField;
    /**
     * Metadescription field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.metadescription
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    metadescription: prismicT.RichTextField;
    /**
     * OG Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.ogImage
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    ogImage: prismicT.ImageField<never>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroSlice | GuestListSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = GuestDocument | PageDocument;
/**
 * Primary content in GuestList → Primary
 *
 */
interface GuestListSliceDefaultPrimary {
    /**
     * Heading field in *GuestList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest_list.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *GuestList → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest_list.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Item in GuestList → Items
 *
 */
export interface GuestListSliceDefaultItem {
    /**
     * Guest field in *GuestList → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: guest_list.items[].guest
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    guest: prismicT.RelationField;
}
/**
 * Default variation for GuestList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `GuestList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GuestListSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<GuestListSliceDefaultPrimary>, Simplify<GuestListSliceDefaultItem>>;
/**
 * Slice variation for *GuestList*
 *
 */
type GuestListSliceVariation = GuestListSliceDefault;
/**
 * GuestList Shared Slice
 *
 * - **API ID**: `guest_list`
 * - **Description**: `GuestList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GuestListSlice = prismicT.SharedSlice<"guest_list", GuestListSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Heading field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { GuestDocumentData, GuestDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, GuestListSliceDefaultPrimary, GuestListSliceDefaultItem, GuestListSliceDefault, GuestListSliceVariation, GuestListSlice, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice };
    }
}
