// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Guest documents */
interface GuestDocumentData {
    /**
     * Name field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Avatar field in *Guest*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.avatar
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    avatar: prismicT.ImageField<never>;
    /**
     * Job Title field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.jobTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    jobTitle: prismicT.KeyTextField;
    /**
     * Guest Bio field in *Guest*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.guestBio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    guestBio: prismicT.RichTextField;
    /**
     * Twitter URL field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.twitterUrl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    twitterUrl: prismicT.KeyTextField;
    /**
     * Website URL field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.websiteUrl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    websiteUrl: prismicT.KeyTextField;
    /**
     * Mastadon URL field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.mastadonUrl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    mastadonUrl: prismicT.KeyTextField;
    /**
     * Topic Title field in *Guest*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.topicTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    topicTitle: prismicT.KeyTextField;
    /**
     * Topic Description field in *Guest*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest.topicDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    topicDescription: prismicT.RichTextField;
}
/**
 * Guest document from Prismic
 *
 * - **API ID**: `guest`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GuestDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<GuestDocumentData>, "guest", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Page title
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
    /**
     * Metatitle field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.metatitle
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metatitle: prismicT.KeyTextField;
    /**
     * Metadescription field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.metadescription
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    metadescription: prismicT.RichTextField;
    /**
     * OG Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.ogImage
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    ogImage: prismicT.ImageField<never>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroSlice | GuestListSlice | SponsorListSlice | EventDetailsSlice | CharityDetailsSlice | RegisterCtaSlice | LastYearRecapSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Sponsor documents */
interface SponsorDocumentData {
    /**
     * Name field in *Sponsor*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sponsor.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Logo field in *Sponsor*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: sponsor.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Link field in *Sponsor*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: sponsor.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Sponsor document from Prismic
 *
 * - **API ID**: `sponsor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SponsorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SponsorDocumentData>, "sponsor", Lang>;
export type AllDocumentTypes = GuestDocument | PageDocument | SponsorDocument;
/**
 * Primary content in CharityDetails → Primary
 *
 */
interface CharityDetailsSliceDefaultPrimary {
    /**
     * Heading field in *CharityDetails → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: charity_details.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *CharityDetails → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: charity_details.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
    /**
     * Charity Logo field in *CharityDetails → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: charity_details.primary.charityLogo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    charityLogo: prismicT.ImageField<never>;
}
/**
 * Default variation for CharityDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CharityDetails`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CharityDetailsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CharityDetailsSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CharityDetails*
 *
 */
type CharityDetailsSliceVariation = CharityDetailsSliceDefault;
/**
 * CharityDetails Shared Slice
 *
 * - **API ID**: `charity_details`
 * - **Description**: `CharityDetails`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CharityDetailsSlice = prismicT.SharedSlice<"charity_details", CharityDetailsSliceVariation>;
/**
 * Primary content in EventDetails → Primary
 *
 */
interface EventDetailsSliceDefaultPrimary {
    /**
     * Heading field in *EventDetails → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event_details.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *EventDetails → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event_details.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
    /**
     * Date and Time field in *EventDetails → Primary*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: event_details.primary.dateTime
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    dateTime: prismicT.TimestampField;
    /**
     * Link to Show field in *EventDetails → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: event_details.primary.showLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    showLink: prismicT.LinkField;
}
/**
 * Default variation for EventDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: `EventDetails`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EventDetailsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<EventDetailsSliceDefaultPrimary>, never>;
/**
 * Slice variation for *EventDetails*
 *
 */
type EventDetailsSliceVariation = EventDetailsSliceDefault;
/**
 * EventDetails Shared Slice
 *
 * - **API ID**: `event_details`
 * - **Description**: `EventDetails`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EventDetailsSlice = prismicT.SharedSlice<"event_details", EventDetailsSliceVariation>;
/**
 * Primary content in GuestList → Primary
 *
 */
interface GuestListSliceDefaultPrimary {
    /**
     * Heading field in *GuestList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest_list.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *GuestList → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: guest_list.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Default variation for GuestList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `GuestList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GuestListSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<GuestListSliceDefaultPrimary>, never>;
/**
 * Slice variation for *GuestList*
 *
 */
type GuestListSliceVariation = GuestListSliceDefault;
/**
 * GuestList Shared Slice
 *
 * - **API ID**: `guest_list`
 * - **Description**: `GuestList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GuestListSlice = prismicT.SharedSlice<"guest_list", GuestListSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Heading field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in LastYearRecap → Primary
 *
 */
interface LastYearRecapSliceDefaultPrimary {
    /**
     * Heading field in *LastYearRecap → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: last_year_recap.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *LastYearRecap → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: last_year_recap.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Default variation for LastYearRecap Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LastYearRecap`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LastYearRecapSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LastYearRecapSliceDefaultPrimary>, never>;
/**
 * Slice variation for *LastYearRecap*
 *
 */
type LastYearRecapSliceVariation = LastYearRecapSliceDefault;
/**
 * LastYearRecap Shared Slice
 *
 * - **API ID**: `last_year_recap`
 * - **Description**: `LastYearRecap`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LastYearRecapSlice = prismicT.SharedSlice<"last_year_recap", LastYearRecapSliceVariation>;
/**
 * Primary content in RegisterCTA → Primary
 *
 */
interface RegisterCtaSliceDefaultPrimary {
    /**
     * Heading field in *RegisterCTA → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: register_cta.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *RegisterCTA → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: register_cta.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Default variation for RegisterCTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: `RegisterCTA`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RegisterCtaSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<RegisterCtaSliceDefaultPrimary>, never>;
/**
 * Slice variation for *RegisterCTA*
 *
 */
type RegisterCtaSliceVariation = RegisterCtaSliceDefault;
/**
 * RegisterCTA Shared Slice
 *
 * - **API ID**: `register_cta`
 * - **Description**: `RegisterCTA`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RegisterCtaSlice = prismicT.SharedSlice<"register_cta", RegisterCtaSliceVariation>;
/**
 * Primary content in SponsorList → Primary
 *
 */
interface SponsorListSliceDefaultPrimary {
    /**
     * Heading field in *SponsorList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sponsor_list.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Body field in *SponsorList → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sponsor_list.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Default variation for SponsorList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SponsorList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorListSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SponsorListSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SponsorList*
 *
 */
type SponsorListSliceVariation = SponsorListSliceDefault;
/**
 * SponsorList Shared Slice
 *
 * - **API ID**: `sponsor_list`
 * - **Description**: `SponsorList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorListSlice = prismicT.SharedSlice<"sponsor_list", SponsorListSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { GuestDocumentData, GuestDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, SponsorDocumentData, SponsorDocument, AllDocumentTypes, CharityDetailsSliceDefaultPrimary, CharityDetailsSliceDefault, CharityDetailsSliceVariation, CharityDetailsSlice, EventDetailsSliceDefaultPrimary, EventDetailsSliceDefault, EventDetailsSliceVariation, EventDetailsSlice, GuestListSliceDefaultPrimary, GuestListSliceDefault, GuestListSliceVariation, GuestListSlice, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice, LastYearRecapSliceDefaultPrimary, LastYearRecapSliceDefault, LastYearRecapSliceVariation, LastYearRecapSlice, RegisterCtaSliceDefaultPrimary, RegisterCtaSliceDefault, RegisterCtaSliceVariation, RegisterCtaSlice, SponsorListSliceDefaultPrimary, SponsorListSliceDefault, SponsorListSliceVariation, SponsorListSlice };
    }
}
