// Code generated by Slice Machine. DO NOT EDIT.

import CharityDetails from './CharityDetails';
import EventDetails from './EventDetails';
import GuestList from './GuestList';
import Hero from './Hero';
import LastYearRecap from './LastYearRecap';
import RegisterCTA from './RegisterCTA';
import SponsorList from './SponsorList';

export {
	CharityDetails,
	EventDetails,
	GuestList,
	Hero,
	LastYearRecap,
	RegisterCTA,
	SponsorList,
};

export const components = {
	charity_details: CharityDetails,
	event_details: EventDetails,
	guest_list: GuestList,
	hero: Hero,
	last_year_recap: LastYearRecap,
	register_cta: RegisterCTA,
	sponsor_list: SponsorList,
};
